on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  frontend:
    name: FrontEnd Deployment Job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{vars.AWS_REGION}}
    
    - name: Checking Code Out
      uses: actions/checkout@v4

    - name: Uploading Files to Bucket
      run: aws s3 sync app ${{vars.BUCKET_URL}}

    - name: Creating CloudFront Invalidation
      run: aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'


    
